//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WindowsFormsApplication1
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class BioStarEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto BioStarEntities usando la cadena de conexión encontrada en la sección 'BioStarEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public BioStarEntities() : base("name=BioStarEntities", "BioStarEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BioStarEntities.
        /// </summary>
        public BioStarEntities(string connectionString) : base(connectionString, "BioStarEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BioStarEntities.
        /// </summary>
        public BioStarEntities(EntityConnection connection) : base(connection, "BioStarEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TB_USUARIO> TB_USUARIO
        {
            get
            {
                if ((_TB_USUARIO == null))
                {
                    _TB_USUARIO = base.CreateObjectSet<TB_USUARIO>("TB_USUARIO");
                }
                return _TB_USUARIO;
            }
        }
        private ObjectSet<TB_USUARIO> _TB_USUARIO;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TB_USUARIO. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTB_USUARIO(TB_USUARIO tB_USUARIO)
        {
            base.AddObject("TB_USUARIO", tB_USUARIO);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BioStarModel", Name="TB_USUARIO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_USUARIO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TB_USUARIO.
        /// </summary>
        /// <param name="uSU_ID">Valor inicial de la propiedad USU_ID.</param>
        /// <param name="uSU_NOMBRE">Valor inicial de la propiedad USU_NOMBRE.</param>
        /// <param name="uSU_SEGUNDO_NOMBRE">Valor inicial de la propiedad USU_SEGUNDO_NOMBRE.</param>
        /// <param name="uSU_APELLIDO_PATERNO">Valor inicial de la propiedad USU_APELLIDO_PATERNO.</param>
        /// <param name="uSU_APELLIDO_MATERNO">Valor inicial de la propiedad USU_APELLIDO_MATERNO.</param>
        /// <param name="uSU_RUT">Valor inicial de la propiedad USU_RUT.</param>
        /// <param name="uSU_DV">Valor inicial de la propiedad USU_DV.</param>
        /// <param name="uSU_DEPARTAMENTO">Valor inicial de la propiedad USU_DEPARTAMENTO.</param>
        /// <param name="uSU_USUARIO">Valor inicial de la propiedad USU_USUARIO.</param>
        /// <param name="uSU_CONTRASENA">Valor inicial de la propiedad USU_CONTRASENA.</param>
        /// <param name="uSU_ROL">Valor inicial de la propiedad USU_ROL.</param>
        public static TB_USUARIO CreateTB_USUARIO(global::System.Int32 uSU_ID, global::System.String uSU_NOMBRE, global::System.String uSU_SEGUNDO_NOMBRE, global::System.String uSU_APELLIDO_PATERNO, global::System.String uSU_APELLIDO_MATERNO, global::System.String uSU_RUT, global::System.String uSU_DV, global::System.String uSU_DEPARTAMENTO, global::System.String uSU_USUARIO, global::System.String uSU_CONTRASENA, global::System.String uSU_ROL)
        {
            TB_USUARIO tB_USUARIO = new TB_USUARIO();
            tB_USUARIO.USU_ID = uSU_ID;
            tB_USUARIO.USU_NOMBRE = uSU_NOMBRE;
            tB_USUARIO.USU_SEGUNDO_NOMBRE = uSU_SEGUNDO_NOMBRE;
            tB_USUARIO.USU_APELLIDO_PATERNO = uSU_APELLIDO_PATERNO;
            tB_USUARIO.USU_APELLIDO_MATERNO = uSU_APELLIDO_MATERNO;
            tB_USUARIO.USU_RUT = uSU_RUT;
            tB_USUARIO.USU_DV = uSU_DV;
            tB_USUARIO.USU_DEPARTAMENTO = uSU_DEPARTAMENTO;
            tB_USUARIO.USU_USUARIO = uSU_USUARIO;
            tB_USUARIO.USU_CONTRASENA = uSU_CONTRASENA;
            tB_USUARIO.USU_ROL = uSU_ROL;
            return tB_USUARIO;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 USU_ID
        {
            get
            {
                return _USU_ID;
            }
            set
            {
                if (_USU_ID != value)
                {
                    OnUSU_IDChanging(value);
                    ReportPropertyChanging("USU_ID");
                    _USU_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("USU_ID");
                    OnUSU_IDChanged();
                }
            }
        }
        private global::System.Int32 _USU_ID;
        partial void OnUSU_IDChanging(global::System.Int32 value);
        partial void OnUSU_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_NOMBRE
        {
            get
            {
                return _USU_NOMBRE;
            }
            set
            {
                OnUSU_NOMBREChanging(value);
                ReportPropertyChanging("USU_NOMBRE");
                _USU_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_NOMBRE");
                OnUSU_NOMBREChanged();
            }
        }
        private global::System.String _USU_NOMBRE;
        partial void OnUSU_NOMBREChanging(global::System.String value);
        partial void OnUSU_NOMBREChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_SEGUNDO_NOMBRE
        {
            get
            {
                return _USU_SEGUNDO_NOMBRE;
            }
            set
            {
                OnUSU_SEGUNDO_NOMBREChanging(value);
                ReportPropertyChanging("USU_SEGUNDO_NOMBRE");
                _USU_SEGUNDO_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_SEGUNDO_NOMBRE");
                OnUSU_SEGUNDO_NOMBREChanged();
            }
        }
        private global::System.String _USU_SEGUNDO_NOMBRE;
        partial void OnUSU_SEGUNDO_NOMBREChanging(global::System.String value);
        partial void OnUSU_SEGUNDO_NOMBREChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_APELLIDO_PATERNO
        {
            get
            {
                return _USU_APELLIDO_PATERNO;
            }
            set
            {
                OnUSU_APELLIDO_PATERNOChanging(value);
                ReportPropertyChanging("USU_APELLIDO_PATERNO");
                _USU_APELLIDO_PATERNO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_APELLIDO_PATERNO");
                OnUSU_APELLIDO_PATERNOChanged();
            }
        }
        private global::System.String _USU_APELLIDO_PATERNO;
        partial void OnUSU_APELLIDO_PATERNOChanging(global::System.String value);
        partial void OnUSU_APELLIDO_PATERNOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_APELLIDO_MATERNO
        {
            get
            {
                return _USU_APELLIDO_MATERNO;
            }
            set
            {
                OnUSU_APELLIDO_MATERNOChanging(value);
                ReportPropertyChanging("USU_APELLIDO_MATERNO");
                _USU_APELLIDO_MATERNO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_APELLIDO_MATERNO");
                OnUSU_APELLIDO_MATERNOChanged();
            }
        }
        private global::System.String _USU_APELLIDO_MATERNO;
        partial void OnUSU_APELLIDO_MATERNOChanging(global::System.String value);
        partial void OnUSU_APELLIDO_MATERNOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_RUT
        {
            get
            {
                return _USU_RUT;
            }
            set
            {
                OnUSU_RUTChanging(value);
                ReportPropertyChanging("USU_RUT");
                _USU_RUT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_RUT");
                OnUSU_RUTChanged();
            }
        }
        private global::System.String _USU_RUT;
        partial void OnUSU_RUTChanging(global::System.String value);
        partial void OnUSU_RUTChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_DV
        {
            get
            {
                return _USU_DV;
            }
            set
            {
                OnUSU_DVChanging(value);
                ReportPropertyChanging("USU_DV");
                _USU_DV = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_DV");
                OnUSU_DVChanged();
            }
        }
        private global::System.String _USU_DV;
        partial void OnUSU_DVChanging(global::System.String value);
        partial void OnUSU_DVChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_DEPARTAMENTO
        {
            get
            {
                return _USU_DEPARTAMENTO;
            }
            set
            {
                OnUSU_DEPARTAMENTOChanging(value);
                ReportPropertyChanging("USU_DEPARTAMENTO");
                _USU_DEPARTAMENTO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_DEPARTAMENTO");
                OnUSU_DEPARTAMENTOChanged();
            }
        }
        private global::System.String _USU_DEPARTAMENTO;
        partial void OnUSU_DEPARTAMENTOChanging(global::System.String value);
        partial void OnUSU_DEPARTAMENTOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_USUARIO
        {
            get
            {
                return _USU_USUARIO;
            }
            set
            {
                OnUSU_USUARIOChanging(value);
                ReportPropertyChanging("USU_USUARIO");
                _USU_USUARIO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_USUARIO");
                OnUSU_USUARIOChanged();
            }
        }
        private global::System.String _USU_USUARIO;
        partial void OnUSU_USUARIOChanging(global::System.String value);
        partial void OnUSU_USUARIOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_CONTRASENA
        {
            get
            {
                return _USU_CONTRASENA;
            }
            set
            {
                OnUSU_CONTRASENAChanging(value);
                ReportPropertyChanging("USU_CONTRASENA");
                _USU_CONTRASENA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_CONTRASENA");
                OnUSU_CONTRASENAChanged();
            }
        }
        private global::System.String _USU_CONTRASENA;
        partial void OnUSU_CONTRASENAChanging(global::System.String value);
        partial void OnUSU_CONTRASENAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_ROL
        {
            get
            {
                return _USU_ROL;
            }
            set
            {
                OnUSU_ROLChanging(value);
                ReportPropertyChanging("USU_ROL");
                _USU_ROL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_ROL");
                OnUSU_ROLChanged();
            }
        }
        private global::System.String _USU_ROL;
        partial void OnUSU_ROLChanging(global::System.String value);
        partial void OnUSU_ROLChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USU_COMENTARIO
        {
            get
            {
                return _USU_COMENTARIO;
            }
            set
            {
                OnUSU_COMENTARIOChanging(value);
                ReportPropertyChanging("USU_COMENTARIO");
                _USU_COMENTARIO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USU_COMENTARIO");
                OnUSU_COMENTARIOChanged();
            }
        }
        private global::System.String _USU_COMENTARIO;
        partial void OnUSU_COMENTARIOChanging(global::System.String value);
        partial void OnUSU_COMENTARIOChanged();

        #endregion

    
    }

    #endregion

    
}
